openapi: 3.1.0
info:
  title: Broker API
  version: 1.0.0
servers:
  - url: https://imagegen-gpts-api.vercel.app
paths:
  /api/upsert:
    post:
      operationId: upsertEntry
      summary: Upsert JSON entry to GitHub via Broker
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [owner, repo, branch, path, entry, audit]
              properties:
                owner: { type: string }
                repo: { type: string }
                branch: { type: string }
                path: { type: string }
                entry: { type: object }
                audit: { type: object }
      responses:
        "200":
          description: Success
components:
  securitySchemes:
    brokerApiKey:
      type: http
      scheme: bearer
security:
  - brokerApiKey: []
