openapi: 3.1.0
info:
  title: GitHub Contents API
  version: 1.0.0
servers:
  - url: https://api.github.com
paths:
  /repos/{owner}/{repo}/contents/{path}:
    get:
      operationId: getRepoFile
      summary: Get file content
      parameters:
        - name: owner
          in: path
          required: true
          schema: { type: string }
        - name: repo
          in: path
          required: true
          schema: { type: string }
        - name: path
          in: path
          required: true
          schema: { type: string }
        - name: ref
          in: query
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sha: { type: string }
                  content: { type: string }
    put:
      operationId: putRepoFile
      summary: Create or update file
      parameters:
        - name: owner
          in: path
          required: true
          schema: { type: string }
        - name: repo
          in: path
          required: true
          schema: { type: string }
        - name: path
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message, content]
              properties:
                message: { type: string }
                content: { type: string }
                sha: { type: string }
                branch: { type: string }
      responses:
        "200":
          description: Updated
components:
  securitySchemes:
    githubToken:
      type: http
      scheme: bearer
      bearerFormat: token
security:
  - githubToken: []
