openapi: 3.1.0
info:
  title: Vercel Deploy Hook
  version: 1.0.0
servers:
  - url: https://api.vercel.com
paths:
  /v1/integrations/deploy/{hookId}:
    post:
      operationId: triggerDeploy
      summary: Trigger Vercel deploy
      parameters:
        - name: hookId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: OK
